<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="f0aefd3e-9a05-457c-852c-29b39d229fe2" name="Fredrik@FKVAIO 2010-09-06 13:25:19" runUser="FKVaio\Fredrik" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="5b82bb5d-938d-47a6-8c5b-afaf40dc0149">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Fredrik_FKVAIO 2010-09-06 13_25_19" />
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2010-09-06T13:25:19.1247396+02:00" queuing="2010-09-06T13:25:19.4197565+02:00" start="2010-09-06T13:25:19.6727709+02:00" finish="2010-09-06T13:25:20.1037956+02:00" />
  <ResultSummary outcome="Completed">
    <Counters total="1" executed="1" passed="1" error="0" failed="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="Exception_is_thrown" storage="c:\source\_projects\nexttask\nexttask.tests\bin\debug\nexttask.tests.dll" id="9a3db4a8-9cd3-9603-39d8-1e5ffa3a32fe">
      <Execution timeOut="1800000" id="b94d4440-9651-41a3-ba71-c4a7b52279e3" />
      <TestMethod codeBase="C:/Source/_Projects/NextTask/NextTask.Tests/bin/Debug/NextTask.Tests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="NextTask.Tests.When_postponing_task_in_the_past, NextTask.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="Exception_is_thrown" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="9a3db4a8-9cd3-9603-39d8-1e5ffa3a32fe" executionId="b94d4440-9651-41a3-ba71-c4a7b52279e3" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="b94d4440-9651-41a3-ba71-c4a7b52279e3" testId="9a3db4a8-9cd3-9603-39d8-1e5ffa3a32fe" testName="Exception_is_thrown" computerName="FKVAIO" duration="00:00:00.1769217" startTime="2010-09-06T13:25:19.7567758+02:00" endTime="2010-09-06T13:25:20.0257911+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="b94d4440-9651-41a3-ba71-c4a7b52279e3">
    </UnitTestResult>
  </Results>
</TestRun>